### ISSUE TITLE
How are the config files generated?

### ISSUE THREAD

**Issue by GildedHonour** [tonlabs/tonos-se#8]
How are the initial config files of a SE node generated? By what? What's the algorightm? How do I generate or re-generate them on my own?

**Comment by DezzK** [comment]
The initial config file of Node SE is created manually. Keys are just ed25519-dalek secret and public keys, stored in binary format. You can modify the configuration file https://github.com/tonlabs/tonos-se/blob/master/docker/ton-node/cfg, if you need, for example, to change ports, but you don't need to change keys, because they are only used by ADNL, which is useless in Node SE.
